### How to slice a 1D numpy array

In [1]:

import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [3]:
c = a[1::2]
c

array([1, 3, 5, 7, 9])

In [4]:
d = b+c
d

array([ 1,  5,  9, 13, 17])